### ISSUE TITLE
Add HN Who is hiring threads

### ISSUE THREAD

**Issue by pgagnidze** [Tkko/top_freelance_platforms#2]
<a href="https://news.ycombinator.com/submitted?id=whoishiring"><img width="300" src="https://i.imgur.com/NqwQhfS.png"/></a>
## [Who is hiring?](https://news.ycombinator.com/submitted?id=whoishiring)
**Ask HN: Who is hiring?**\
*Hacker News Who's Hiring is a monthly thread on the Hacker News website where individuals and companies can share job openings and search for potential candidates.*

**Comment by Tkko** [comment]
Done 
Thanks for opening the very first issue 🤘
